export const works = [
  {
    title: 'Yahoo Open HackU (チームハッカソン)',
    link: false,
    linkUrl: 'https://next-website-tau.vercel.app/',
    git: true,
    gitUrl: 'https://github.com/Team-Harinezumi/ssdb-frontend',
    addContent: '現状の魔法のスプレットシートをより見やすく、便利に使える様に作成しました',
    langContent: 'Next.js/　Rails ',
    day: '2021/3',
  },
  {
    title: 'Guild Hack(自分にあったハッカソンに参加しよう)',
    link: false,
    linkUrl: 'https://next-website-tau.vercel.app/',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/HEW_Frontend',
    addContent: '自分にあったハッカソンに参加できるサイトがなかったので作成しました。※僕はフロント担当',
    langContent: 'Next.js　/　Go　/　AWS　',
    day: '2021/2',
  },
  {
    title: 'NextでWebサイト（SSG）',
    link: true,
    linkUrl: 'https://next-website-tau.vercel.app/',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Next_website',
    addContent: '初めてNextjsでSSGを用いて作ってみたかった。',
    langContent: 'Next　/　Tailwind　/　JsonAPI　/　SSG　/　Dynamic route',
    day: '2020/11',
  },
  {
    title: '画像検索アプリ',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Unsplash-image-search-app',
    addContent: '個人開発でUnsplashAPIを使う機会があったので、どんな感じなのか予習がてら作成しました。',
    langContent: 'React　/　axios　/　UnsplashAPI',
    day: '2020/10',
  },
  {
    title: '初めてのチーム制作',
    link: false,
    linkUrl: 'https://next-website-tau.vercel.app/',
    git: true,
    gitUrl: 'https://github.com/HALTimTim/TimTim',
    addContent: 'このチーム制作では、①タスクの管理②チームでやる作業と個人でやる作業の切り分け方③モチベーション管理④ドキュメント作り、などに重きを置いて活動してすごい多くのことを学べました。',
    langContent: 'PHP',
    day: '2020/10',
  },
  {
    title: 'ポケモン図鑑ゲットだぜ❗️❗️',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Pokemon',
    addContent: '個人的にポケモンが好きで、今何種類のポケモンがいるのか気になって作りました。ちなみに898種類もいますww',
    langContent: 'Next.js　/　Tailwind.css　/　PokemonAPI',
    day: '2020/9',
  },
  {
    title: '図書管理システム',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Book-management-system',
    addContent: '学校の課題を改良して図書管理アプリを作成',
    langContent: 'HTML　/　CSS　/　PHP　/　MYSQL',
    day: '2020/8',
  },
  {
    title: 'TRELLO風TODOリスト',
    link: true,
    linkUrl: 'https://muchan-trello.netlify.app/',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Vue-Trello',
    addContent: 'ReactとVueでどう違うのかを認識したかったので、Vueを用いてタスク管理アプリを作成。',
    langContent: 'Vue　/　Vuex　/　Vuetify　/　draggable',
    day: '2020/9',
  },
  {
    title: 'LARAVELでブログ作ちゃったよ',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Laravel-Blog',
    addContent: '初めてのLaravelアウトプット',
    langContent: 'HTML　/　CSS　/　PHP　/　Laravel',
    day:'2020/8',
  },
  {
    title: '学内コンテスト金賞の作品(てんとう虫パーク)',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: false,
    gitUrl: 'https://hongmuchan.net',
    addContent: '現状のてんとう虫パークよりもっと見やすくWebサイトにしたくて作成しました。',
    langContent: 'HTML　/　CSS　/　JS　/　PHP　/　MYSQL　/　GoogleMapAPI',
    day:'2020/2',
  },
  {
    title: '天気APIで世界天気を取得しちゃおう',
    link: false,
    linkUrl: 'https://hongmuchan.net',
    git: true,
    gitUrl: 'https://github.com/HongMuchang/Weather-API',
    addContent: 'APIを初めて知って、APIとは何かを理解するために天気っ取得アプリ作成しました。',
    langContent: 'HTML　/　CSS　/　JS　/　OpenWeatherMapAPI',
    day:'2019/7',
  },
]